// ai-suggestion:unverified · session:01a0f5ce-3321-7bd1-9738-1f28ad96ef6b/agent:clipboard_core · 2026-10-01
import AppKit
import Carbon
import Foundation
import UniformTypeIdentifiers

/// Samples newly copied content, without ever materializing a speakfree paste promise.
/// This is a best-effort observer, not a system event log or an authenticated writer API.
final class ClipboardHistoryMonitor {
    static let historyMarker = NSPasteboard.PasteboardType("com.definitelyreal.speakfree.history")
    static let ignoredTypes: Set<String> = {
        var types: Set<String> = [
        "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType", "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping", "Pasteboard generator type", "net.antelle.keeweb",
        "com.agilebits.onepassword", historyMarker.rawValue,
        "com.definitelyreal.speakfree.clipboard-owner"
        ]
        // AppKit normalizes old pasteboard flavor names to dynamic UTIs when
        // publishing them. Check that spelling too, before asking providers for data.
        for conformance: UTType? in [nil, .data] {
            if let generator = UTType(tag: "Pasteboard generator type",
                                      tagClass: UTTagClass(rawValue: "com.apple.nspboard-type"),
                                      conformingTo: conformance) {
                types.insert(generator.identifier)
            }
        }
        return types
    }()
    static let defaultExcludedApplications: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "com.lastpass.lastpass", "com.dashlane.dashlanephonefinal",
        "com.apple.passwords", "org.keepassxc.keepassxc", "com.strongbox.strongbox"
    ]

    var sourceAppBundleID: () -> String? = { NSWorkspace.shared.frontmostApplication?.bundleIdentifier }
    /// True only for a currently owned generation. A new external copy should stay observable.
    var isClipboardBorrowed: () -> Bool = { false }
    /// Independent of clipboard marker cooperation; injected tests never alter system state.
    var secureInputIsActive: () -> Bool = { IsSecureEventInputEnabled() }
    var excludedApplications = defaultExcludedApplications
    var onStatusChange: ((String?) -> Void)?
    private(set) var status: String?

    /// Injectable to exercise deny behavior without touching system permission settings.
    var accessIsDenied: () -> Bool

    private let pasteboard: NSPasteboard
    private let store: HistoryStore
    private let readerQueue = DispatchQueue(label: "com.definitelyreal.speakfree.history-reader", qos: .utility)
    private var timer: Timer?
    private var enabled = false
    private var suspensionDepth = 0
    private var generation: UInt64 = 0
    private var lastChangeCount: Int
    private var lastSource: String?
    private var ignoredChanges: [Int] = []
    private var readInFlight = false
    private var activeRead: ReadCancellation?

    /// Main invalidates a capture while its provider reads run on the reader queue.
    /// No AppKit call is made under this lock. An already-running read cannot be
    /// interrupted, but invalidation prevents materializing the following promises.
    private final class ReadCancellation: @unchecked Sendable {
        private let lock = NSLock()
        private var cancelled = false
        var isCancelled: Bool {
            lock.lock(); defer { lock.unlock() }
            return cancelled
        }
        func cancel() {
            lock.lock(); defer { lock.unlock() }
            cancelled = true
        }
    }

    init(pasteboard: NSPasteboard, store: HistoryStore) {
        precondition(Thread.isMainThread)
        self.pasteboard = pasteboard
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
        self.accessIsDenied = {
            if #available(macOS 15.4, *) { return pasteboard.accessBehavior == .alwaysDeny }
            return false
        }
    }

    deinit { timer?.invalidate(); activeRead?.cancel() }

    func start() {
        precondition(Thread.isMainThread)
        guard timer == nil else { return }
        baseline()
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.pollNow() }
        self.timer = timer
        RunLoop.main.add(timer, forMode: .common)
    }

    func stop() {
        precondition(Thread.isMainThread)
        timer?.invalidate()
        timer = nil
        invalidateRead()
        baseline()
    }

    func setEnabled(_ value: Bool) {
        precondition(Thread.isMainThread)
        guard enabled != value else { return }
        enabled = value
        invalidateRead()
        baseline()
        setStatus(nil)
    }

    func suspend() {
        precondition(Thread.isMainThread)
        suspensionDepth += 1
        invalidateRead()
        baseline()
    }

    /// Resume always starts from the current generation, never harvesting an old clipboard.
    func resume() {
        precondition(Thread.isMainThread)
        suspensionDepth = max(0, suspensionDepth - 1)
        invalidateRead()
        baseline()
    }

    func ignore(changeCount: Int) {
        precondition(Thread.isMainThread)
        ignoredChanges.append(changeCount)
        if ignoredChanges.count > 64 { ignoredChanges.removeFirst(ignoredChanges.count - 64) }
    }

    /// Call when NSWorkspace reports an activation, before the user makes their next copy.
    /// This records the transition immediately instead of discarding that subsequent copy
    /// at the next polling tick. Existing clipboard contents remain outside the new app's
    /// attribution, and any capture still pending for the old app is invalidated.
    func applicationDidActivate() {
        precondition(Thread.isMainThread)
        invalidateRead()
        baseline()
    }

    func pollNow() {
        precondition(Thread.isMainThread)
        guard enabled, store.policy.captureClipboard, suspensionDepth == 0 else { baseline(); return }
        // Do not even inspect advertised types while a secure-entry context is active.
        // Baseline rather than harvesting its old clipboard when Secure Input ends.
        guard !secureInputIsActive() else {
            invalidateRead()
            baseline()
            return
        }
        let source = sourceAppBundleID()?.lowercased()
        let count = pasteboard.changeCount
        // A foreground transition means we cannot confidently apply an app exclusion to this
        // generation. Skip it without reading. Background writers remain inherently ambiguous.
        guard source == lastSource else { baseline(); return }
        guard count != lastChangeCount else { return }
        guard !readInFlight else { return } // Pick up the latest generation on the next tick.
        lastChangeCount = count
        guard !ignoredChanges.contains(count), !isClipboardBorrowed() else { return }
        guard !accessIsDenied() else {
            setStatus("Clipboard access is denied in System Settings. Dictation history remains available.")
            return
        }
        guard source.map({ !excludedApplications.contains($0) }) ?? true else { return }

        // Check the root type list, then every item's type list, BEFORE requesting any bytes.
        // Types-only lookup does not call DictationPasteProvider.provideDataForType.
        let rootTypes = pasteboard.types ?? []
        guard !Self.shouldIgnore(types: rootTypes, excludedApplications: excludedApplications) else { return }
        guard let items = pasteboard.pasteboardItems, !items.isEmpty, items.count <= 512 else { return }
        let typesByItem = items.map(\.types)
        guard !typesByItem.contains(where: { Self.shouldIgnore(types: $0, excludedApplications: excludedApplications) }) else { return }
        let offeredByItem = typesByItem.map { $0.filter { HistoryEntry.supportedTypes.contains($0.rawValue) } }
        // Many image writers promise a cheap PNG and a very large, lazily expanded TIFF.
        // Keep their original lossless PNG without asking the writer to materialize TIFF.
        // We do not make the same substitution for JPEG/HEIC: those may be lossy, so TIFF
        // remains part of their capture and the whole item can still exceed the size cap.
        let omittedByItem = offeredByItem.map { offered in
            offered.contains(.png) ? offered.filter { ["public.tiff", "NSTIFFPboardType"].contains($0.rawValue) } : []
        }
        let supportedByItem = zip(offeredByItem, omittedByItem).map { offered, omitted in
            offered.filter { !omitted.contains($0) }
        }
        guard supportedByItem.allSatisfy({ !$0.isEmpty && $0.count <= 64 }) else {
            setStatus("This clipboard item uses a format that history cannot save yet.")
            return
        }
        guard pasteboard.changeCount == count, !isClipboardBorrowed() else { return }
        let token = generation
        let byteLimit = min(store.policy.maximumEntryBytes, store.policy.maximumBytes)
        readInFlight = true
        let cancellation = ReadCancellation()
        activeRead = cancellation
        let board = pasteboard
        readerQueue.async { [weak self] in
            var saved: [HistoryPasteboardItem] = []
            var bytes = 0
            var failure: String?
            itemLoop: for (index, item) in items.enumerated() {
                let types = supportedByItem[index]
                var representations: [HistoryRepresentation] = []
                for type in types {
                    guard !cancellation.isCancelled, board.changeCount == count else { break itemLoop }
                    let data = item.data(forType: type)
                    guard !cancellation.isCancelled, board.changeCount == count else { break itemLoop }
                    guard let data else {
                        failure = "A clipboard representation could not be read. This item was not saved."
                        break itemLoop
                    }
                    // AppKit has no byte-length preflight. One lazy representation may allocate
                    // before this check; it is not retained if it exceeds the entry bound.
                    guard data.count <= byteLimit - bytes else {
                        let preservesTIFF = types.contains { ["public.tiff", "NSTIFFPboardType"].contains($0.rawValue) }
                            && types.contains { ["public.jpeg", "public.heic"].contains($0.rawValue) }
                        failure = "This clipboard item is too large for history and was not saved."
                            + (preservesTIFF ? " JPEG or HEIC with TIFF keeps both formats to avoid silently reducing quality." : "")
                        break itemLoop
                    }
                    bytes += data.count
                    representations.append(.init(type: type.rawValue, data: data))
                }
                saved.append(.init(representations: representations,
                                   omittedRepresentationTypes: omittedByItem[index].map(\.rawValue)))
            }
            DispatchQueue.main.async {
                guard let self else { return }
                self.readInFlight = false
                if self.activeRead === cancellation { self.activeRead = nil }
                guard !self.secureInputIsActive() else {
                    self.invalidateRead()
                    self.baseline()
                    return
                }
                guard self.enabled, self.store.policy.captureClipboard, self.suspensionDepth == 0,
                      token == self.generation, board.changeCount == count,
                      self.sourceAppBundleID()?.lowercased() == source,
                      !self.ignoredChanges.contains(count), !self.isClipboardBorrowed() else { return }
                if let failure { self.setStatus(failure); return }
                guard saved.count == items.count else { return }
                self.store.addClipboard(items: saved, sourceAppBundleID: source)
                self.setStatus(nil)
            }
        }
    }

    /// A testing barrier that waits for the reader's completion to reach the main run loop.
    func flushForTesting(completion: @escaping () -> Void) {
        readerQueue.async { DispatchQueue.main.async(execute: completion) }
    }

    private func invalidateRead() {
        generation &+= 1
        activeRead?.cancel()
    }

    private func baseline() {
        lastChangeCount = pasteboard.changeCount
        lastSource = sourceAppBundleID()?.lowercased()
    }

    private func setStatus(_ value: String?) {
        guard status != value else { return }
        status = value
        onStatusChange?(value)
    }

    private static func shouldIgnore(types: [NSPasteboard.PasteboardType], excludedApplications: Set<String>) -> Bool {
        types.contains { type in
            if ignoredTypes.contains(type.rawValue) { return true }
            let value = type.rawValue.lowercased()
            return excludedApplications.contains { $0 == value || $0.hasPrefix(value + ".") }
        }
    }
}
