// ai-suggestion:unverified · Claude · 2026-09-25 · feat/fast-clipboard
//
// "Can the first read of speakfree's clipboard promise be trusted as the target app's paste?"
// (internal design notes, approach A).
//
// Two inputs decide it:
//   1. A table of clipboard readers by bundle ID, sorted three ways: respects the
//      Transient/Concealed/AutoGenerated markers, ignores them, or unknown. Checked per paste
//      against the running apps (no permission, microseconds).
//   2. The local canary (ClipboardCanary.swift): a harmless item shaped exactly like a dictation,
//      written while the screen is locked or the Mac is idle. A read means some reader on THIS Mac
//      ignores the markers. The canary's result overrides the table.
//
// Privacy: nothing here holds clipboard content. Results are outcomes, timings and bundle IDs.

import AppKit
import Foundation

// MARK: - The table

enum ClipboardReaderCompliance: String, Codable, Equatable {
    /// Skips items carrying the nspasteboard.org markers (measured or documented).
    case respectsMarkers = "respects markers"
    /// Reads every clipboard change regardless of markers (VM/KVM clipboard sync, remote viewers).
    case ignoresMarkers = "ignores markers"
    /// A clipboard history tool whose behavior with the markers is not verified.
    case unknown = "unknown"
}

struct ClipboardReader: Equatable {
    let bundleID: String
    let name: String
    let compliance: ClipboardReaderCompliance
    /// Where the classification comes from, for the diagnostic.
    let evidence: String
}

enum ClipboardReaderCatalog {
    /// Clipboard history tools. "respects" needs a measurement or the tool's own documentation;
    /// everything else stays "unknown" until a canary or a user report says otherwise.
    /// Sources: nspasteboard.org's list of marker-aware apps (fetched 2026-09-25), and the
    /// canary probes on a development Mac 2026-09-25 (Clipy and Raycast: 0 of 10 marked writes read,
    /// 22 of 22 unmarked writes read).
    static let managers: [ClipboardReader] = [
        ClipboardReader(bundleID: "org.p0deje.Maccy", name: "Maccy", compliance: .respectsMarkers,
                        evidence: "source: ignores the three marker types by default"),
        ClipboardReader(bundleID: "com.clipy-app.Clipy", name: "Clipy", compliance: .respectsMarkers,
                        evidence: "measured 2026-09-25"),
        ClipboardReader(bundleID: "com.raycast.macos", name: "Raycast", compliance: .respectsMarkers,
                        evidence: "measured 2026-09-25"),
        // Documented as not STORING marked items (nspasteboard.org), which does not prove they
        // skip READING the text first (the read is what fires the receipt). Unknown until measured.
        ClipboardReader(bundleID: "com.runningwithcrayons.Alfred", name: "Alfred", compliance: .unknown,
                        evidence: "nspasteboard.org: does not store marked items; read unmeasured"),
        ClipboardReader(bundleID: "com.wiheads.paste", name: "Paste", compliance: .unknown,
                        evidence: "nspasteboard.org: does not store marked items; read unmeasured"),
        ClipboardReader(bundleID: "com.wiheads.paste-setapp", name: "Paste (Setapp)", compliance: .unknown,
                        evidence: "nspasteboard.org: does not store marked items; read unmeasured"),
        ClipboardReader(bundleID: "com.tapbots.Pastebot2Mac", name: "Pastebot", compliance: .unknown,
                        evidence: "not verified"),
        ClipboardReader(bundleID: "at.obdev.LaunchBar", name: "LaunchBar", compliance: .unknown,
                        evidence: "not verified"),
        ClipboardReader(bundleID: "com.stairways.keyboardmaestro.engine", name: "Keyboard Maestro Engine",
                        compliance: .unknown, evidence: "not verified (writes markers; history reader unverified)"),
        ClipboardReader(bundleID: "com.fiplab.clipboard", name: "CopyClip", compliance: .unknown,
                        evidence: "not verified"),
        ClipboardReader(bundleID: "com.fiplab.copyclip2", name: "CopyClip 2", compliance: .unknown,
                        evidence: "not verified"),
        ClipboardReader(bundleID: "com.generalarcade.flycut", name: "Flycut", compliance: .unknown,
                        evidence: "not verified"),
        ClipboardReader(bundleID: "net.sf.Jumpcut", name: "Jumpcut", compliance: .unknown,
                        evidence: "not verified"),
        ClipboardReader(bundleID: "com.naotaka.ClipMenu", name: "ClipMenu", compliance: .unknown,
                        evidence: "not verified"),
        ClipboardReader(bundleID: "com.hegenberg.BetterTouchTool", name: "BetterTouchTool", compliance: .unknown,
                        evidence: "not verified (optional clipboard manager)"),
        ClipboardReader(bundleID: "com.softwareambience.Unclutter", name: "Unclutter", compliance: .unknown,
                        evidence: "not verified"),
    ]

    /// Every reader the table knows, including the eager syncers `AppCompatibility` lists.
    static var all: [ClipboardReader] {
        managers + AppCompatibility.clipboardSyncerBundleIDs.sorted().map {
            ClipboardReader(bundleID: $0, name: $0, compliance: .ignoresMarkers,
                            evidence: "copies the clipboard to another machine on every change")
        }
    }

    static func sorted(_ compliance: ClipboardReaderCompliance) -> [ClipboardReader] {
        all.filter { $0.compliance == compliance }
    }

    /// The table's entry for one running app, or nil when it is not a known clipboard reader.
    /// Remote viewers that sync eagerly count as ignoring the markers (`isClipboardSyncer`).
    static func reader(bundleID: String?) -> ClipboardReader? {
        guard let bundleID, !bundleID.isEmpty else { return nil }
        let lower = bundleID.lowercased()
        if let manager = managers.first(where: { $0.bundleID.lowercased() == lower }) { return manager }
        if AppCompatibility.isClipboardSyncer(bundleID: bundleID) {
            return ClipboardReader(bundleID: bundleID, name: bundleID, compliance: .ignoresMarkers,
                                   evidence: "copies the clipboard to another machine on every change")
        }
        return nil
    }

    /// Per-bundle-ID memo of `reader(bundleID:)`: the per-paste check sees the same few hundred
    /// running apps every time, and classifying each from scratch cost ~5 ms per paste on main
    /// (measured, 402 apps). The table is static, so a memo never goes stale.
    private static let memoLock = NSLock()
    private static var memo: [String: ClipboardReader?] = [:]

    static func cachedReader(bundleID: String) -> ClipboardReader? {
        memoLock.lock()
        if let hit = memo[bundleID] { memoLock.unlock(); return hit }
        memoLock.unlock()
        let found = reader(bundleID: bundleID)
        memoLock.lock()
        if memo.count > 4096 { memo.removeAll() }
        memo[bundleID] = .some(found)
        memoLock.unlock()
        return found
    }

    static func running(in bundleIDs: [String?]) -> [ClipboardReader] {
        var seen = Set<String>()
        return bundleIDs.compactMap { $0.flatMap(cachedReader(bundleID:)) }
            .filter { seen.insert($0.bundleID.lowercased()).inserted }
    }
}

// MARK: - Canary results

struct ClipboardCanaryResult: Codable, Equatable {
    enum Outcome: String, Codable { case read, clean, inconclusive }
    enum Mode: String, Codable { case lock, idle }

    let date: Date
    let mode: Mode
    let outcome: Outcome
    /// Milliseconds from the write to the first read, when something read it.
    let readAfterMs: Int?
    /// Whether the user's clipboard was put back (false: something else wrote first; left alone).
    let restored: Bool
    /// Known clipboard readers running at the time (bundle IDs, lowercased).
    let readers: [String]
    /// Why a run was inconclusive (a short code, never content).
    let note: String?
    /// How long the canary was held (ms). Only long holds can vouch for a reader (a short
    /// window can fall between a slowed-down poller's reads). nil in results from older builds.
    var holdMs: Int? = nil
}

/// What the canary history says about this Mac.
enum ClipboardCanaryVerdict: Equatable {
    /// No conclusive run yet: the table decides.
    case none
    /// The latest conclusive runs were clean. `coveredReaders` were running during one of them,
    /// so the canary vouches for them even when the table does not.
    case trusted(coveredReaders: Set<String>)
    /// Something read a canary, and fewer than `cleanRunsToRecover` clean runs have come since.
    case untrusted
}

/// Canary history plus the once-a-day bookkeeping. Persisted as a small JSON file next to
/// config.json (never inside it), so a canary never races a Settings save.
struct ClipboardTrustState: Codable, Equatable {
    var results: [ClipboardCanaryResult] = []
    var lastAttemptAt: Date?

    static let maxResults = 20
    /// After a read, the fast path stays off until this many clean runs in a row.
    static let cleanRunsToRecover = 3
    /// A reader is vouched for only after this many clean runs with it running...
    static let cleanRunsToCover = 2
    /// ...within this long (a reader can change behavior with an update).
    static let coverageMaxAge: TimeInterval = 30 * 24 * 60 * 60
    /// ...and only runs held at least this long count (lock-mode runs hold 20 s; idle-mode runs,
    /// 2 s, can catch a reader but never vouch for one).
    static let minimumCoveringHoldMs = 15_000

    /// Oldest inconclusive runs are dropped first, so a read is never pushed out by runs that
    /// decided nothing.
    mutating func append(_ result: ClipboardCanaryResult) {
        results.append(result)
        while results.count > Self.maxResults {
            if let index = results.firstIndex(where: { $0.outcome == .inconclusive }) {
                results.remove(at: index)
            } else {
                results.removeFirst()
            }
        }
    }

    var verdict: ClipboardCanaryVerdict { verdict(now: Date()) }

    func verdict(now: Date) -> ClipboardCanaryVerdict {
        let conclusive = results.filter { $0.outcome != .inconclusive }
        guard !conclusive.isEmpty else { return .none }
        var clean = ArraySlice(conclusive)
        if let lastRead = conclusive.lastIndex(where: { $0.outcome == .read }) {
            clean = conclusive[(lastRead + 1)...]
            // Any run can catch a reader, but only long holds count toward clearing one: a short
            // idle window can fall between a slowed-down poller's reads.
            let longClean = clean.filter { ($0.holdMs ?? 0) >= Self.minimumCoveringHoldMs }
            guard longClean.count >= Self.cleanRunsToRecover else { return .untrusted }
        }
        var counts: [String: Int] = [:]
        for run in clean where now.timeIntervalSince(run.date) < Self.coverageMaxAge
            && (run.holdMs ?? 0) >= Self.minimumCoveringHoldMs {
            for reader in Set(run.readers) { counts[reader, default: 0] += 1 }
        }
        return .trusted(coveredReaders: Set(counts.filter { $0.value >= Self.cleanRunsToCover }.keys))
    }
}

// MARK: - The decision

enum ClipboardTrust {
    /// Why the first read must NOT be trusted right now, or nil when it may be. Pure.
    /// The canary overrides the table: a read turns the fast path off even when every running
    /// reader is marked as respecting the markers, and repeated recent clean runs vouch for
    /// "unknown" managers that were running during them.
    static func untrustedReason(running: [ClipboardReader], verdict: ClipboardCanaryVerdict) -> String? {
        if verdict == .untrusted { return "canary-read" }
        var covered = Set<String>()
        if case .trusted(let readers) = verdict { covered = readers }
        // Clean runs vouch only for "unknown" managers, never for an eager syncer: a suspended VM
        // or an unconnected viewer reads nothing while the screen is locked, and its silence
        // then says nothing about tomorrow.
        for reader in running where reader.compliance != .respectsMarkers {
            if reader.compliance == .unknown, covered.contains(reader.bundleID.lowercased()) { continue }
            switch reader.compliance {
            case .ignoresMarkers: return "syncer:\(reader.bundleID)"
            case .unknown: return "unknown-reader:\(reader.bundleID)"
            case .respectsMarkers: continue
            }
        }
        return nil
    }

    /// The support text for Report a Problem's "Copy Report": which clipboard readers run, what
    /// the canary found, and whether the fast restore is on. Never any clipboard content.
    static func diagnosticText(running: [ClipboardReader], state: ClipboardTrustState, now: Date = Date()) -> String {
        var lines = ["**Clipboard**"]
        if running.isEmpty {
            lines.append("- Known clipboard readers running: none")
        } else {
            for reader in running {
                lines.append("- Running: \(reader.name) (\(reader.bundleID)): \(reader.compliance.rawValue), \(reader.evidence)")
            }
        }
        // Day only: the exact times would tell a public issue when this Mac gets locked.
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withFullDate]
        if state.results.isEmpty {
            lines.append("- Clipboard canary: not run yet")
        } else {
            for result in state.results.suffix(5) {
                var line = "- Canary \(formatter.string(from: result.date)) (\(result.mode.rawValue)): \(result.outcome.rawValue)"
                if let ms = result.readAfterMs { line += " after \(ms) ms" }
                if let note = result.note { line += " [\(note)]" }
                if !result.restored { line += ", clipboard left alone (changed by something else)" }
                lines.append(line)
            }
        }
        let verdict: String
        switch state.verdict {
        case .none: verdict = "no conclusive run"
        case .trusted(let covered) where covered.isEmpty: verdict = "clean (not yet enough runs to vouch for any reader)"
        case .trusted(let covered): verdict = "clean, vouches for: \(covered.sorted().joined(separator: ", "))"
        case .untrusted: verdict = "a reader ignored the markers"
        }
        lines.append("- Canary verdict: \(verdict)")
        let reason = untrustedReason(running: running, verdict: state.verdict)
        lines.append("- Fast clipboard restore on first read: " + (reason.map { "off (\($0))" } ?? "on"))
        return lines.joined(separator: "\n")
    }
}

// MARK: - Store

/// Main-thread owner of the persisted canary state. `fileURL` nil keeps it in memory only
/// (tests, and any test process that would otherwise resolve the real config directory).
final class ClipboardTrustStore {
    static let shared = ClipboardTrustStore(fileURL: ClipboardTrustStore.defaultFileURL())

    private let fileURL: URL?
    private var loaded = false
    private var cached = ClipboardTrustState()

    init(fileURL: URL?, initial: ClipboardTrustState = ClipboardTrustState()) {
        self.fileURL = fileURL
        self.cached = initial
        if fileURL == nil { loaded = true }
    }

    static func defaultFileURL() -> URL? {
        // Never read or write the developer's real ~/.config/speakfree from a test process.
        guard !Config.isResolvingRealDirUnderTest else { return nil }
        return Config.configDir.appendingPathComponent("clipboard-trust.json")
    }

    var state: ClipboardTrustState {
        if !loaded {
            loaded = true
            if let fileURL, let data = try? Data(contentsOf: fileURL) {
                let decoder = JSONDecoder()
                decoder.dateDecodingStrategy = .iso8601
                if let decoded = try? decoder.decode(ClipboardTrustState.self, from: data) { cached = decoded }
            }
        }
        return cached
    }

    func update(_ change: (inout ClipboardTrustState) -> Void) {
        var next = state
        change(&next)
        cached = next
        guard let fileURL else { return }
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        guard let data = try? encoder.encode(next) else { return }
        try? FileManager.default.createDirectory(at: fileURL.deletingLastPathComponent(),
                                                 withIntermediateDirectories: true)
        try? data.write(to: fileURL, options: .atomic)
    }

    /// Production per-paste check: running apps against the table, then the canary verdict.
    func currentUntrustedReason(runningBundleIDs: [String?] = NSWorkspace.shared.runningApplications.map(\.bundleIdentifier))
        -> String? {
        ClipboardTrust.untrustedReason(running: ClipboardReaderCatalog.running(in: runningBundleIDs),
                                       verdict: state.verdict)
    }

    func diagnosticText(runningBundleIDs: [String?] = NSWorkspace.shared.runningApplications.map(\.bundleIdentifier))
        -> String {
        ClipboardTrust.diagnosticText(running: ClipboardReaderCatalog.running(in: runningBundleIDs), state: state)
    }
}
