// ai-suggestion:unverified · Claude · 2026-09-24 · feat/fast-clipboard
import AppKit

/// Supplies a dictation's text to the pasteboard lazily, so speakfree learns the moment a
/// process reads it (the "read receipt" that lets the user's clipboard come back early).
///
/// Measured on macOS 26 (internal clipboard research): AppKit calls
/// `pasteboard(_:item:provideDataForType:)` on the main thread, once; a types-only query does not
/// call it; after the first read the pasteboard server caches the text and serves later reads
/// (same or other process) itself. So this sees the FIRST read only, and it always hands out
/// exactly the text it was created with, never anything newer or older.
final class DictationPasteProvider: NSObject, NSPasteboardItemDataProvider {
    /// nspasteboard.org markers: clipboard-history tools skip the item from its type list.
    static let markerTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// True while speakfree itself reads the clipboard (`TextInserter.withOwnPasteboardRead`).
    /// Main thread only. Such a read is served but is not a receipt.
    static var ownReadInProgress = false

    let text: String
    /// Number of times AppKit asked for the text (normally 0 or 1; see the caching note above).
    private(set) var provideCount = 0
    /// Reads that count as a receipt (`provideCount` minus speakfree's own reads).
    private(set) var receiptCount = 0
    /// Called on the main thread for each read that counts as a receipt.
    var onRead: (() -> Void)?

    init(text: String) {
        self.text = text
    }

    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem,
                    provideDataForType type: NSPasteboard.PasteboardType) {
        // Serve the data first and unconditionally: the reader is blocked on us.
        item.setString(text, forType: type)
        let counts = !(Thread.isMainThread && Self.ownReadInProgress)
        let record = { [weak self] in
            guard let self else { return }
            self.provideCount += 1
            if counts {
                self.receiptCount += 1
                self.onRead?()
            }
        }
        // Receipt bookkeeping only ever runs on main (the pending-restore state lives there).
        // Observed: AppKit already calls this on main. Never mutate the pasteboard from here.
        if Thread.isMainThread { record() } else { DispatchQueue.main.async(execute: record) }
    }

    func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}
}
